# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('link', models.URLField(default='', max_length=50, verbose_name='链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='cover',
            field=models.ImageField(upload_to='static/images/banner/', verbose_name='轮播图'),
        ),
    ]
